[package]
name = "ageing_sim"
version = "0.1.0"
authors = ["BartÅ‚omiej KamiÅ„ski <fizyk20@gmail.com>"]

[dependencies]
rand = "0.3"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
tiny-keccak = "1.4"
